<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'permission_access',],
            ['id' => 3, 'title' => 'permission_create',],
            ['id' => 4, 'title' => 'permission_edit',],
            ['id' => 5, 'title' => 'permission_view',],
            ['id' => 6, 'title' => 'permission_delete',],
            ['id' => 7, 'title' => 'role_access',],
            ['id' => 8, 'title' => 'role_create',],
            ['id' => 9, 'title' => 'role_edit',],
            ['id' => 10, 'title' => 'role_view',],
            ['id' => 11, 'title' => 'role_delete',],
            ['id' => 12, 'title' => 'user_access',],
            ['id' => 13, 'title' => 'user_create',],
            ['id' => 14, 'title' => 'user_edit',],
            ['id' => 15, 'title' => 'user_view',],
            ['id' => 16, 'title' => 'user_delete',],
            ['id' => 17, 'title' => 'contact_management_access',],
            ['id' => 18, 'title' => 'contact_management_create',],
            ['id' => 19, 'title' => 'contact_management_edit',],
            ['id' => 20, 'title' => 'contact_management_view',],
            ['id' => 21, 'title' => 'contact_management_delete',],
            ['id' => 22, 'title' => 'contact_company_access',],
            ['id' => 23, 'title' => 'contact_company_create',],
            ['id' => 24, 'title' => 'contact_company_edit',],
            ['id' => 25, 'title' => 'contact_company_view',],
            ['id' => 26, 'title' => 'contact_company_delete',],
            ['id' => 27, 'title' => 'contact_access',],
            ['id' => 28, 'title' => 'contact_create',],
            ['id' => 29, 'title' => 'contact_edit',],
            ['id' => 30, 'title' => 'contact_view',],
            ['id' => 31, 'title' => 'contact_delete',],
            ['id' => 32, 'title' => 'internal_notification_access',],
            ['id' => 33, 'title' => 'internal_notification_create',],
            ['id' => 34, 'title' => 'internal_notification_edit',],
            ['id' => 35, 'title' => 'internal_notification_view',],
            ['id' => 36, 'title' => 'internal_notification_delete',],
            ['id' => 37, 'title' => 'content_management_access',],
            ['id' => 38, 'title' => 'content_management_create',],
            ['id' => 39, 'title' => 'content_management_edit',],
            ['id' => 40, 'title' => 'content_management_view',],
            ['id' => 41, 'title' => 'content_management_delete',],
            ['id' => 42, 'title' => 'content_category_access',],
            ['id' => 43, 'title' => 'content_category_create',],
            ['id' => 44, 'title' => 'content_category_edit',],
            ['id' => 45, 'title' => 'content_category_view',],
            ['id' => 46, 'title' => 'content_category_delete',],
            ['id' => 47, 'title' => 'content_tag_access',],
            ['id' => 48, 'title' => 'content_tag_create',],
            ['id' => 49, 'title' => 'content_tag_edit',],
            ['id' => 50, 'title' => 'content_tag_view',],
            ['id' => 51, 'title' => 'content_tag_delete',],
            ['id' => 52, 'title' => 'content_page_access',],
            ['id' => 53, 'title' => 'content_page_create',],
            ['id' => 54, 'title' => 'content_page_edit',],
            ['id' => 55, 'title' => 'content_page_view',],
            ['id' => 56, 'title' => 'content_page_delete',],
            ['id' => 57, 'title' => 'ads_dashboard_access',],
            ['id' => 58, 'title' => 'channel_access',],
            ['id' => 59, 'title' => 'channel_create',],
            ['id' => 60, 'title' => 'channel_edit',],
            ['id' => 61, 'title' => 'channel_view',],
            ['id' => 62, 'title' => 'channel_delete',],
            ['id' => 63, 'title' => 'management_access',],
            ['id' => 64, 'title' => 'profile_access',],
            ['id' => 65, 'title' => 'profile_create',],
            ['id' => 66, 'title' => 'profile_edit',],
            ['id' => 67, 'title' => 'profile_view',],
            ['id' => 68, 'title' => 'profile_delete',],
            ['id' => 69, 'title' => 'client_management_access',],
            ['id' => 70, 'title' => 'client_management_create',],
            ['id' => 71, 'title' => 'client_management_edit',],
            ['id' => 72, 'title' => 'client_management_view',],
            ['id' => 73, 'title' => 'client_management_delete',],
            ['id' => 74, 'title' => 'client_management_setting_access',],
            ['id' => 75, 'title' => 'client_management_setting_create',],
            ['id' => 76, 'title' => 'client_management_setting_edit',],
            ['id' => 77, 'title' => 'client_management_setting_view',],
            ['id' => 78, 'title' => 'client_management_setting_delete',],
            ['id' => 79, 'title' => 'client_currency_access',],
            ['id' => 80, 'title' => 'client_currency_create',],
            ['id' => 81, 'title' => 'client_currency_edit',],
            ['id' => 82, 'title' => 'client_currency_view',],
            ['id' => 83, 'title' => 'client_currency_delete',],
            ['id' => 84, 'title' => 'client_transaction_type_access',],
            ['id' => 85, 'title' => 'client_transaction_type_create',],
            ['id' => 86, 'title' => 'client_transaction_type_edit',],
            ['id' => 87, 'title' => 'client_transaction_type_view',],
            ['id' => 88, 'title' => 'client_transaction_type_delete',],
            ['id' => 89, 'title' => 'client_income_source_access',],
            ['id' => 90, 'title' => 'client_income_source_create',],
            ['id' => 91, 'title' => 'client_income_source_edit',],
            ['id' => 92, 'title' => 'client_income_source_view',],
            ['id' => 93, 'title' => 'client_income_source_delete',],
            ['id' => 94, 'title' => 'client_status_access',],
            ['id' => 95, 'title' => 'client_status_create',],
            ['id' => 96, 'title' => 'client_status_edit',],
            ['id' => 97, 'title' => 'client_status_view',],
            ['id' => 98, 'title' => 'client_status_delete',],
            ['id' => 99, 'title' => 'client_project_status_access',],
            ['id' => 100, 'title' => 'client_project_status_create',],
            ['id' => 101, 'title' => 'client_project_status_edit',],
            ['id' => 102, 'title' => 'client_project_status_view',],
            ['id' => 103, 'title' => 'client_project_status_delete',],
            ['id' => 104, 'title' => 'client_access',],
            ['id' => 105, 'title' => 'client_create',],
            ['id' => 106, 'title' => 'client_edit',],
            ['id' => 107, 'title' => 'client_view',],
            ['id' => 108, 'title' => 'client_delete',],
            ['id' => 109, 'title' => 'client_project_access',],
            ['id' => 110, 'title' => 'client_project_create',],
            ['id' => 111, 'title' => 'client_project_edit',],
            ['id' => 112, 'title' => 'client_project_view',],
            ['id' => 113, 'title' => 'client_project_delete',],
            ['id' => 114, 'title' => 'client_note_access',],
            ['id' => 115, 'title' => 'client_note_create',],
            ['id' => 116, 'title' => 'client_note_edit',],
            ['id' => 117, 'title' => 'client_note_view',],
            ['id' => 118, 'title' => 'client_note_delete',],
            ['id' => 119, 'title' => 'client_document_access',],
            ['id' => 120, 'title' => 'client_document_create',],
            ['id' => 121, 'title' => 'client_document_edit',],
            ['id' => 122, 'title' => 'client_document_view',],
            ['id' => 123, 'title' => 'client_document_delete',],
            ['id' => 124, 'title' => 'assets_category_access',],
            ['id' => 125, 'title' => 'assets_category_create',],
            ['id' => 126, 'title' => 'assets_category_edit',],
            ['id' => 127, 'title' => 'assets_category_view',],
            ['id' => 128, 'title' => 'assets_category_delete',],
            ['id' => 129, 'title' => 'assets_management_access',],
            ['id' => 130, 'title' => 'assets_management_create',],
            ['id' => 131, 'title' => 'assets_management_edit',],
            ['id' => 132, 'title' => 'assets_management_view',],
            ['id' => 133, 'title' => 'assets_management_delete',],
            ['id' => 134, 'title' => 'client_transaction_access',],
            ['id' => 135, 'title' => 'client_transaction_create',],
            ['id' => 136, 'title' => 'client_transaction_edit',],
            ['id' => 137, 'title' => 'client_transaction_view',],
            ['id' => 138, 'title' => 'client_transaction_delete',],
            ['id' => 139, 'title' => 'assets_status_access',],
            ['id' => 140, 'title' => 'assets_status_create',],
            ['id' => 141, 'title' => 'assets_status_edit',],
            ['id' => 142, 'title' => 'assets_status_view',],
            ['id' => 143, 'title' => 'assets_status_delete',],
            ['id' => 144, 'title' => 'assets_location_access',],
            ['id' => 145, 'title' => 'assets_location_create',],
            ['id' => 146, 'title' => 'assets_location_edit',],
            ['id' => 147, 'title' => 'assets_location_view',],
            ['id' => 148, 'title' => 'assets_location_delete',],
            ['id' => 149, 'title' => 'asset_access',],
            ['id' => 150, 'title' => 'asset_create',],
            ['id' => 151, 'title' => 'asset_edit',],
            ['id' => 152, 'title' => 'asset_view',],
            ['id' => 153, 'title' => 'asset_delete',],
            ['id' => 154, 'title' => 'assets_history_access',],
            ['id' => 155, 'title' => 'assets_history_create',],
            ['id' => 156, 'title' => 'assets_history_edit',],
            ['id' => 157, 'title' => 'assets_history_view',],
            ['id' => 158, 'title' => 'assets_history_delete',],
            ['id' => 159, 'title' => 'ad_access',],
            ['id' => 160, 'title' => 'ad_create',],
            ['id' => 161, 'title' => 'ad_edit',],
            ['id' => 162, 'title' => 'ad_view',],
            ['id' => 163, 'title' => 'ad_delete',],
            ['id' => 164, 'title' => 'ad_type_access',],
            ['id' => 165, 'title' => 'ad_type_create',],
            ['id' => 166, 'title' => 'ad_type_edit',],
            ['id' => 167, 'title' => 'ad_type_view',],
            ['id' => 168, 'title' => 'ad_type_delete',],
            ['id' => 169, 'title' => 'team_access',],
            ['id' => 170, 'title' => 'team_create',],
            ['id' => 171, 'title' => 'team_edit',],
            ['id' => 172, 'title' => 'team_view',],
            ['id' => 173, 'title' => 'team_delete',],
            ['id' => 174, 'title' => 'audience_access',],
            ['id' => 175, 'title' => 'audience_create',],
            ['id' => 176, 'title' => 'audience_edit',],
            ['id' => 177, 'title' => 'audience_view',],
            ['id' => 178, 'title' => 'audience_delete',],
            ['id' => 179, 'title' => 'demographic_access',],
            ['id' => 180, 'title' => 'demographic_create',],
            ['id' => 181, 'title' => 'demographic_edit',],
            ['id' => 182, 'title' => 'demographic_view',],
            ['id' => 183, 'title' => 'demographic_delete',],
            ['id' => 189, 'title' => 'default_setting_access',],
            ['id' => 190, 'title' => 'user_base_access',],
            ['id' => 191, 'title' => 'user_base_create',],
            ['id' => 192, 'title' => 'user_base_edit',],
            ['id' => 193, 'title' => 'user_base_view',],
            ['id' => 194, 'title' => 'user_base_delete',],
            ['id' => 195, 'title' => 'variable_access',],
            ['id' => 196, 'title' => 'variable_create',],
            ['id' => 197, 'title' => 'variable_edit',],
            ['id' => 198, 'title' => 'variable_view',],
            ['id' => 199, 'title' => 'variable_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
