<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'permission_access',],
            ['id' => 3, 'title' => 'permission_create',],
            ['id' => 4, 'title' => 'permission_edit',],
            ['id' => 5, 'title' => 'permission_view',],
            ['id' => 6, 'title' => 'permission_delete',],
            ['id' => 7, 'title' => 'role_access',],
            ['id' => 8, 'title' => 'role_create',],
            ['id' => 9, 'title' => 'role_edit',],
            ['id' => 10, 'title' => 'role_view',],
            ['id' => 11, 'title' => 'role_delete',],
            ['id' => 12, 'title' => 'user_access',],
            ['id' => 13, 'title' => 'user_create',],
            ['id' => 14, 'title' => 'user_edit',],
            ['id' => 15, 'title' => 'user_view',],
            ['id' => 16, 'title' => 'user_delete',],
            ['id' => 17, 'title' => 'contact_management_access',],
            ['id' => 18, 'title' => 'contact_management_create',],
            ['id' => 19, 'title' => 'contact_management_edit',],
            ['id' => 20, 'title' => 'contact_management_view',],
            ['id' => 21, 'title' => 'contact_management_delete',],
            ['id' => 22, 'title' => 'contact_company_access',],
            ['id' => 23, 'title' => 'contact_company_create',],
            ['id' => 24, 'title' => 'contact_company_edit',],
            ['id' => 25, 'title' => 'contact_company_view',],
            ['id' => 26, 'title' => 'contact_company_delete',],
            ['id' => 27, 'title' => 'contact_access',],
            ['id' => 28, 'title' => 'contact_create',],
            ['id' => 29, 'title' => 'contact_edit',],
            ['id' => 30, 'title' => 'contact_view',],
            ['id' => 31, 'title' => 'contact_delete',],
            ['id' => 32, 'title' => 'internal_notification_access',],
            ['id' => 33, 'title' => 'internal_notification_create',],
            ['id' => 34, 'title' => 'internal_notification_edit',],
            ['id' => 35, 'title' => 'internal_notification_view',],
            ['id' => 36, 'title' => 'internal_notification_delete',],
            ['id' => 37, 'title' => 'content_management_access',],
            ['id' => 38, 'title' => 'content_management_create',],
            ['id' => 39, 'title' => 'content_management_edit',],
            ['id' => 40, 'title' => 'content_management_view',],
            ['id' => 41, 'title' => 'content_management_delete',],
            ['id' => 42, 'title' => 'content_category_access',],
            ['id' => 43, 'title' => 'content_category_create',],
            ['id' => 44, 'title' => 'content_category_edit',],
            ['id' => 45, 'title' => 'content_category_view',],
            ['id' => 46, 'title' => 'content_category_delete',],
            ['id' => 47, 'title' => 'content_tag_access',],
            ['id' => 48, 'title' => 'content_tag_create',],
            ['id' => 49, 'title' => 'content_tag_edit',],
            ['id' => 50, 'title' => 'content_tag_view',],
            ['id' => 51, 'title' => 'content_tag_delete',],
            ['id' => 52, 'title' => 'content_page_access',],
            ['id' => 53, 'title' => 'content_page_create',],
            ['id' => 54, 'title' => 'content_page_edit',],
            ['id' => 55, 'title' => 'content_page_view',],
            ['id' => 56, 'title' => 'content_page_delete',],
            ['id' => 57, 'title' => 'ads_dashboard_access',],
            ['id' => 63, 'title' => 'management_access',],
            ['id' => 70, 'title' => 'client_management_create',],
            ['id' => 71, 'title' => 'client_management_edit',],
            ['id' => 72, 'title' => 'client_management_view',],
            ['id' => 73, 'title' => 'client_management_delete',],
            ['id' => 75, 'title' => 'client_management_setting_create',],
            ['id' => 76, 'title' => 'client_management_setting_edit',],
            ['id' => 77, 'title' => 'client_management_setting_view',],
            ['id' => 78, 'title' => 'client_management_setting_delete',],
            ['id' => 79, 'title' => 'client_currency_access',],
            ['id' => 80, 'title' => 'client_currency_create',],
            ['id' => 81, 'title' => 'client_currency_edit',],
            ['id' => 82, 'title' => 'client_currency_view',],
            ['id' => 83, 'title' => 'client_currency_delete',],
            ['id' => 130, 'title' => 'assets_management_create',],
            ['id' => 131, 'title' => 'assets_management_edit',],
            ['id' => 132, 'title' => 'assets_management_view',],
            ['id' => 133, 'title' => 'assets_management_delete',],
            ['id' => 159, 'title' => 'ad_access',],
            ['id' => 160, 'title' => 'ad_create',],
            ['id' => 161, 'title' => 'ad_edit',],
            ['id' => 162, 'title' => 'ad_view',],
            ['id' => 163, 'title' => 'ad_delete',],
            ['id' => 169, 'title' => 'team_access',],
            ['id' => 170, 'title' => 'team_create',],
            ['id' => 171, 'title' => 'team_edit',],
            ['id' => 172, 'title' => 'team_view',],
            ['id' => 173, 'title' => 'team_delete',],
            ['id' => 174, 'title' => 'audience_access',],
            ['id' => 175, 'title' => 'audience_create',],
            ['id' => 176, 'title' => 'audience_edit',],
            ['id' => 177, 'title' => 'audience_view',],
            ['id' => 178, 'title' => 'audience_delete',],
            ['id' => 179, 'title' => 'demographic_access',],
            ['id' => 180, 'title' => 'demographic_create',],
            ['id' => 181, 'title' => 'demographic_edit',],
            ['id' => 182, 'title' => 'demographic_view',],
            ['id' => 183, 'title' => 'demographic_delete',],
            ['id' => 189, 'title' => 'default_setting_access',],
            ['id' => 190, 'title' => 'user_base_access',],
            ['id' => 191, 'title' => 'user_base_create',],
            ['id' => 192, 'title' => 'user_base_edit',],
            ['id' => 193, 'title' => 'user_base_view',],
            ['id' => 194, 'title' => 'user_base_delete',],
            ['id' => 195, 'title' => 'variable_access',],
            ['id' => 196, 'title' => 'variable_create',],
            ['id' => 197, 'title' => 'variable_edit',],
            ['id' => 198, 'title' => 'variable_view',],
            ['id' => 199, 'title' => 'variable_delete',],
            ['id' => 200, 'title' => 'response_datum_access',],
            ['id' => 202, 'title' => 'network_access',],
            ['id' => 203, 'title' => 'network_create',],
            ['id' => 204, 'title' => 'network_edit',],
            ['id' => 205, 'title' => 'network_view',],
            ['id' => 206, 'title' => 'network_delete',],
            ['id' => 207, 'title' => 'network_stat_access',],
            ['id' => 208, 'title' => 'provider_access',],
            ['id' => 209, 'title' => 'provider_create',],
            ['id' => 210, 'title' => 'provider_edit',],
            ['id' => 211, 'title' => 'provider_view',],
            ['id' => 212, 'title' => 'provider_delete',],
            ['id' => 213, 'title' => 'station_access',],
            ['id' => 214, 'title' => 'station_create',],
            ['id' => 215, 'title' => 'station_edit',],
            ['id' => 216, 'title' => 'station_view',],
            ['id' => 217, 'title' => 'station_delete',],
            ['id' => 218, 'title' => 'ad_response_access',],
            ['id' => 219, 'title' => 'ad_response_create',],
            ['id' => 220, 'title' => 'ad_response_edit',],
            ['id' => 221, 'title' => 'ad_response_view',],
            ['id' => 222, 'title' => 'ad_response_delete',],
            ['id' => 223, 'title' => 'clipdb_access',],
            ['id' => 224, 'title' => 'clipdb_create',],
            ['id' => 225, 'title' => 'clipdb_edit',],
            ['id' => 226, 'title' => 'clipdb_view',],
            ['id' => 227, 'title' => 'clipdb_delete',],
            ['id' => 233, 'title' => 'agent_access',],
            ['id' => 234, 'title' => 'agent_create',],
            ['id' => 235, 'title' => 'agent_edit',],
            ['id' => 236, 'title' => 'agent_view',],
            ['id' => 237, 'title' => 'agent_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
